name: 'Test AWS Credentials'

on:
  push:
    branches: [ "master" ]

jobs:
  test-aws:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test AWS Credentials
        run: aws sts get-caller-identity
